// <auto-generated />
using System;
using BancoDigital.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BancoDigital.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BancoDigital.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("BancoDigital.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.HasKey("Id")
                        .HasName("pk_contas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_contas_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_numero");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("BancoDigital.Domain.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_destino_id");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_origem_id");

                    b.Property<DateTimeOffset>("RealizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_transferencias");

                    b.HasIndex("ContaDestinoId")
                        .HasDatabaseName("ix_transferencias_conta_destino_id");

                    b.HasIndex("ContaOrigemId")
                        .HasDatabaseName("ix_transferencias_conta_origem_id");

                    b.ToTable("transferencias", (string)null);
                });

            modelBuilder.Entity("BancoDigital.Domain.Entities.Conta", b =>
                {
                    b.HasOne("BancoDigital.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contas_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BancoDigital.Domain.Entities.Transferencia", b =>
                {
                    b.HasOne("BancoDigital.Domain.Entities.Conta", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transferencias_contas_conta_destino_id");

                    b.HasOne("BancoDigital.Domain.Entities.Conta", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transferencias_contas_conta_origem_id");

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");
                });
#pragma warning restore 612, 618
        }
    }
}
